controllers:
    resource: ../src/
    type: attribute
    schemes:
        - HTTP
        - HTTPS
    exclude:
        - '../src/Modules/*/Application/Commands/**'
        - '../src/Modules/*/Domain/**'
        - '../src/Modules/*/Infrastructure/**'
